#
# Update the versions in this file.
#

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - install.yaml
  - install-validating-webhook.yaml

# images:
#   - name: quay.io/argoproj/argo-events
#     newTag: latest

# patchesStrategicMerge:
#   - |-
#     apiVersion: apps/v1
#     kind: Deployment
#     metadata:
#       name: controller-manager
#     spec:
#       template:
#         spec:
#           containers:
#             - name: controller-manager
#               env:
#                 - name: ARGO_EVENTS_IMAGE
#                   value: quay.io/argoproj/argo-events:latest
