apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: github
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  github:
    argo-workflow-creation:
      owner: sharadhirao
      repository: argo-combined
      webhook:
        # Endpoint listening to events
        endpoint: /
        port: "12000"
        method: GET
        url: https://argoevents.localhost.com
      events:
        - "*"
#       apiToken:
#         name: github-access
#         key: token
      insecure: true
      active: true
      contentType: json
